### ISSUE TITLE
Solve kattis problem 1 - Classrooms

### ISSUE THREAD

**Issue by avborup** [adbo-ITU/APS23-exam#2]
- [x] Working solution
- [ ] Clean-up code

**Comment by JoachimBorup** [comment]
Turns out Heritage is also a DP problem. Another option is [Classrooms](https://open.kattis.com/problems/classrooms), which looks like a greedy scheduling problem.

**Comment by JoachimBorup** [comment]
Turns out Heritage is also a DP problem. Another option is [Classrooms](https://open.kattis.com/problems/classrooms), which looks like a greedy scheduling problem.
