### ISSUE TITLE
Choose kattis problems to solve

### ISSUE THREAD

**Issue by AMB-F** [adbo-ITU/APS23-exam#5]
Choose three, midlevel difficulty kattis exercises to solve. 
Ensure that the three problems cover separate topics, that are also different from the one used in our own created problem. 
Start by looking at earlier weeks and old programming competitions like NCPC and find problems, that no groupmember has solved before

- [ ] Chose problem 1 - 
- [x] Chose problem 2 - Barshelf
- [x] Chose problem 3 - Restaurent Orders

For topic-based inspiration see https://cpbook.net/methodstosolve

**Comment by AMB-F** [comment]
Some suggestions
### What does it mean/heritage
https://itu.kattis.com/courses/BAPS/APS23/assignments/ytaau4/problems/heritage
Difficulty on open: 5.0
Topic: String algorithms
From earlier week, solved by three course members

**Comment by avborup** [comment]
I would love if we could somehow include [Bar Shelf](https://open.kattis.com/problems/barshelf). I think it's a really interesting solution, which covers multiple Fenwick trees used in conjunction with each other *and* index compression.

Difficulty on open: 7.5 (even with 2000+ submissions)
Topic: Range queries
From: Week 8, solved by 4 people in that contest

The only iffy part.. I already solved it. Is that a problem if it's a difficult problem which I also spent a long time to solve?

Edit: We have officially received approval to use this problem in the exam project - and we are even encouraged to do it 🙌

**Comment by avborup** [comment]
Third: dynamic programming

Exercises from week 3

Restaurent orders
Difficulty: 5.6
Solved by 1 person in course

Knapsack 
Difficulty: 5.1
Solved by 1 person in course

Pepple solitare 1+2 probably too easy with difficulty easy 2.3 and medium 2.9

Tight words
Difficulty: Medium 3.3
Solved by 5 people in the course

**Comment by AMB-F** [comment]
Done, three problems chosen

**Comment by AMB-F** [comment]
Done, three problems chosen

**Comment by AMB-F** [comment]
We have chosen to exchange the problem heritage due to a number of reasons

- Our initial idea for a solution turned out to not be viable, due to a misunderstanding of the problem
- After a conversations with our TA we found out that heritage is actually a dynamic programming problem, and we already have one in this category
- Since last week we have been toying with the idea of doing a greedy problem instead

**Comment by AMB-F** [comment]
We have chosen to exchange the problem heritage due to a number of reasons

- Our initial idea for a solution turned out to not be viable, due to a misunderstanding of the problem
- After a conversations with our TA we found out that heritage is actually a dynamic programming problem, and we already have one in this category
- Since last week we have been toying with the idea of doing a greedy problem instead

**Comment by AMB-F** [comment]
Greedy problem candidates

TA advice regarding difficulty: 
Stay in medium, greedy will inherently have lower difficulty. 3-5 should be fine 

Intergalactic bidding (solved by TA last year, currently 3.5)
Birds on a wire (medium, 3.5)
Classrooms (scheduling, 9.6)
