### ISSUE TITLE
Make problem description

### ISSUE THREAD

**Issue by AMB-F** [adbo-ITU/APS23-exam#7]
Write a full problem description including

- [x] Title
- [x] Backstory
- [x] Input section - include bounds for input variables
- [x] Output section
- [x] Scoring information
- [x] Flavour picture
- [x] Illustration showing the scene and exit and a solution for the route

**Comment by AMB-F** [comment]
Possible backstories and titles

"One copenhell of a problem"
A band of algorithm-students are finishing their last concert at Copenhell, before they must hurry back to the univeristy for their final exam in the course "Heavy Metalgorithmic Problemsolving". The problem is that they are running late, so they have to crowdsurf away from the stage, to make it in time. How many students will miss their exam, because they can't crowdsurf away?

"Cowsurfing"
Copenhell for farm animals

"Meowsurfing"
Copenhell for kittens

"Heavy metalgorithmic problemsolving"
A metal band full of nerds are discussing how effectively they can crowdsurf away from the stage at the end of their conecert

**Comment by AMB-F** [comment]
One Copenhell of a Problem

This year the annual metal festival Copenhell will be closed by the band SOMETHINGAPS, that consists solely of student from the nearby IT University. The concert is a huge success, which has resulted in a huge problem for all the band members! 
The plan was for all of them to attend their final exam in the course "Heavy Metalgorithmic Problemsolving" after ending their concert, but due to the huge demand for encores they are now running late. The only way for them to reach their exam in time is  for them to take advantage of the audience in front of them and crowdsurf all the way from the stage and to the back of the crowd.  Since it is the end of a long festival, all the crowd-members have pretty tired arms from lifting beers and throwing devil-horns, meaning that they can only help lift at most one band member. 
How many band members will miss their exams, due to not being able to crowdsurf safely all the way to the back of the crowd?

**Comment by avborup** [comment]
Would it be an idea to say something like "The band members are drinking beer, but as they are crowdsurfing, they spill beer on the crowd members that carry them along. Unfortunately, the crowd members don't enjoy being doused in beer and thus refuse to carry another band member once they have already helped carry one.
